INSERT INTO `shops` (
        `id`,
        `owner_id`,
        `name`,
        `slug`,
        `description`,
        `cover_image`,
        `logo`,
        `is_active`,
        `address`,
        `settings`,
        `notifications`,
        `created_at`,
        `updated_at`
    )
VALUES (
        1,
        1,
        'Blythe Knowles',
        'chic-haven-boutique',
        'Iste dolor quaerat u',
        '{\"id\": 9, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/9/Untitled-4.jpg\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/9/conversions/Untitled-4-thumbnail.jpg\"}',
        '{\"thumbnail\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/333\\/conversions\\/logo04-thumbnail.jpg\",\"original\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/333\\/logo04.png\",\"id\":333,\"file_name\":\"logo04.png\"}',
        1,
        '{\"country\":\"Expedita tempora occ\",\"city\":\"Nisi esse voluptate\",\"state\":\"Voluptas natus et re\",\"zip\":\"50848\",\"street_address\":\"Qui vel non sunt as\"}',
        '{\"notifications\":[],\"contact\":\"2779888888888\",\"website\":\"https:\\/\\/www.wypiceky.me\",\"socials\":[],\"location\":[]}',
        NULL,
        '2021-10-09 16:24:30',
        '2023-11-22 12:01:47'
    ),
    (
        2,
        1,
        'Urban Threads Emporium',
        'urban-threads-emporium',
        'Elevate your urban style at Urban Threads Emporium.From streetwear essentials to statement pieces, our emporium offers a diverse range of contemporary fashion.Unleash your individuality with our carefully curated selection.',
        '{\"id\": 16, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/16/Untitled-3.jpg\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/16/conversions/Untitled-3-thumbnail.jpg\"}',
        '{\"id\": 15, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/15/fashion.png\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/15/conversions/fashion-thumbnail.jpg\"}',
        1,
        '{\"zip\": \"02210\", \"city\": \"Boston\", \"state\": \"Massachusetts\", \"country\": \"USA\", \"street_address\": \"4360 Hampton Meadows\"}',
        '{\"contact\": \"01236547852\", \"socials\": [], \"website\": null, \"location\": []}',
        NULL,
        '2021-10-09 16:57:34',
        '2023-11-21 12:19:36'
    ),
    (
        3,
        1,
        'Anthony Dudley',
        'velvet-vogue-closet',
        'Quod aliquid et mini',
        '{\"thumbnail\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/338\\/conversions\\/shop-banner011-thumbnail.jpg\",\"original\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/338\\/shop-banner011.png\",\"id\":338,\"file_name\":\"shop-banner011.png\"}',
        '{\"thumbnail\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/342\\/conversions\\/logo08-thumbnail.jpg\",\"original\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/342\\/logo08.png\",\"id\":342,\"file_name\":\"logo08.png\"}',
        1,
        '{\"country\":\"Veniam inventore od\",\"city\":\"Laboris officiis sun\",\"state\":\"Reprehenderit ipsum\",\"zip\":\"96275\",\"street_address\":\"Necessitatibus quia\"}',
        '{\"notifications\":[],\"contact\":\"214876556\",\"website\":\"https:\\/\\/www.ketyky.org.au\",\"socials\":[{\"icon\":\"InstagramIcon\",\"url\":\"Iusto illum dolor o\"}],\"location\":[]}',
        NULL,
        '2021-06-27 03:46:14',
        '2023-11-22 12:04:56'
    ),
    (
        4,
        1,
        'Boho Bliss Emporium',
        'boho-bliss-emporium',
        'The clothing shop is the best shop around the city. This is being run under the store owner and our aim is to provide quality product and hassle free customer service.',
        '{\"id\": \"886\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/884/Untitled-4.jpg\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/884/conversions/Untitled-4-thumbnail.jpg\"}',
        '{\"id\": \"896\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/894/fashion.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/894/conversions/fashion-thumbnail.jpg\"}',
        1,
        '{\"country\":\"USA\",\"city\":\"Lincoln\",\"state\":\"Illinois\",\"zip\":\"62656\",\"street_address\":\"4885  Spring Street\"}',
        '{\"notifications\":{\"email\":null},\"contact\":\"212901921221\",\"website\":\"https:\\/\\/redq.io\",\"socials\":[{\"icon\":\"FacebookIcon\",\"url\":\"https:\\/\\/www.facebook.com\\/\"}],\"location\":{\"lat\":40.1576691,\"lng\":-89.38529779999999,\"city\":\"Lincoln\",\"state\":\"IL\",\"country\":\"United States\",\"formattedAddress\":\"IL-121, Lincoln, IL, USA\"}}',
        NULL,
        '2021-06-27 03:47:10',
        '2023-11-21 12:19:51'
    ),
    (
        5,
        1,
        'Sleek Streetwear Co.',
        'sleek-streetwear-co',
        'Step into urban sophistication with Sleek Streetwear Co. Our curated collection blends street style with sleek design, offering a range of contemporary streetwear. Redefine your urban wardrobe with our stylish essentials.',
        '{\"id\": \"889\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/887/Untitled-1-%281%29.jpg\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/887/conversions/Untitled-1-%281%29-thumbnail.jpg\"}',
        '{\"id\": \"888\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/886/Backpack.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/886/conversions/Backpack-thumbnail.jpg\"}',
        1,
        '{\"country\":\"USA\",\"city\":\"Michigan\",\"state\":\"Alabama\",\"zip\":\"35203\",\"street_address\":\"1740  Bedford Street\"}',
        '{\"notifications\":{\"email\":null},\"contact\":\"212901921221\",\"website\":\"https:\\/\\/redq.io\",\"socials\":[{\"icon\":\"FacebookIcon\",\"url\":\"https:\\/\\/www.facebook.com\\/\"},{\"icon\":\"InstagramIcon\",\"url\":\"https:\\/\\/www.instagram.com\\/\"}],\"location\":{\"lat\":-37.1374024,\"lng\":174.9685924,\"zip\":\"2579\",\"city\":\"Ramarama\",\"state\":\"Auckland\",\"country\":\"New Zealand\",\"formattedAddress\":\"Waharau Lane, Ramarama 2579, New Zealand\"}}',
        NULL,
        '2021-06-27 03:47:23',
        '2023-11-21 12:19:48'
    ),
    (
        6,
        1,
        'Ethereal Essence Boutique',
        'ethereal-essence-boutique',
        'Discover ethereal beauty at Ethereal Essence Boutique. Our collection of exquisite designs and delicate silhouettes transports you to a realm of timeless elegance. Embrace the enchantment of fashion with our ethereal pieces.',
        '{\"id\": \"890\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/888/Untitled-3.jpg\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/888/conversions/Untitled-3-thumbnail.jpg\"}',
        '{\"id\": \"891\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/889/Makeup.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/889/conversions/Makeup-thumbnail.jpg\"}',
        1,
        '{\"country\":\"USA\",\"city\":\"Metairie\",\"state\":\"Louisiana\",\"zip\":\"70001\",\"street_address\":\"2960  Rose Avenue\"}',
        '{\"notifications\":{\"email\":null},\"contact\":\"7196321822\",\"website\":\"https:\\/\\/redq.io\",\"socials\":[{\"icon\":\"InstagramIcon\",\"url\":\"https:\\/\\/www.instagram.com\\/\"},{\"icon\":\"TwitterIcon\",\"url\":\"https:\\/\\/www.twitter.com\\/\"}],\"location\":{\"lat\":51.5176117,\"lng\":-0.210149,\"state\":\"England\",\"country\":\"United Kingdom\",\"formattedAddress\":\"Ladbroke Grove, London, UK\"}}',
        NULL,
        '2021-06-27 03:47:49',
        '2023-11-21 12:19:46'
    ),
    (
        7,
        1,
        'Xena Ochoa',
        'casual-comfort-corner',
        'Explicabo Aut aliqu',
        '{\"thumbnail\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/336\\/conversions\\/shop-banner07-thumbnail.jpg\",\"original\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/336\\/shop-banner07.png\",\"id\":336,\"file_name\":\"shop-banner07.png\"}',
        '{\"thumbnail\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/344\\/conversions\\/logo4-thumbnail.jpg\",\"original\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/344\\/logo4.png\",\"id\":344,\"file_name\":\"logo4.png\"}',
        1,
        '{\"country\":\"Ipsam enim elit acc\",\"city\":\"Aut perferendis haru\",\"state\":\"Voluptatem consequat\",\"zip\":\"97375\",\"street_address\":\"Quod accusantium pra\"}',
        '{\"notifications\":[],\"contact\":\"743000007766\",\"website\":\"https:\\/\\/www.wohykulomiqin.cc\",\"socials\":[{\"icon\":\"FacebookIcon\",\"url\":\"Ipsam delectus occa\"},{\"icon\":\"InstagramIcon\",\"url\":\"Culpa corrupti qui\"}],\"location\":[]}',
        NULL,
        '2021-06-27 03:48:11',
        '2023-11-23 03:57:48'
    ),
    (
        8,
        1,
        'Lavinia Burch',
        'velvet-vibes-emporium',
        'Qui eum dicta asperi',
        '{\"thumbnail\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/334\\/conversions\\/shop-banner04-thumbnail.jpg\",\"original\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/334\\/shop-banner04.png\",\"id\":334,\"file_name\":\"shop-banner04.png\"}',
        '{\"id\": \"893\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/891/Group-36321.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/891/conversions/Group-36321-thumbnail.jpg\"}',
        1,
        '{\"country\":\"Sint totam inventor\",\"city\":\"Provident do in del\",\"state\":\"Adipisci aliquip odi\",\"zip\":\"49970\",\"street_address\":\"Sed dolores sit des\"}',
        '{\"notifications\":{\"email\":null},\"contact\":\"7399999999999\",\"website\":\"https:\\/\\/www.nog.ca\",\"socials\":[{\"icon\":\"FacebookIcon\",\"url\":\"Incidunt commodo vi\"},{\"icon\":\"InstagramIcon\",\"url\":\"Illum ut molestias\"},{\"icon\":\"TwitterIcon\",\"url\":\"Fuga Voluptas et qu\"}],\"location\":[]}',
        NULL,
        '2021-06-27 03:48:23',
        '2023-11-22 12:02:32'
    ),
    (
        9,
        1,
        'Claire Miranda',
        'denim-delight-co',
        'Et consequatur sunt',
        '{\"thumbnail\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/332\\/conversions\\/shop-banner03-thumbnail.jpg\",\"original\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/332\\/shop-banner03.png\",\"id\":332,\"file_name\":\"shop-banner03.png\"}',
        '{\"id\": 1613, \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1613/Publisher-logo.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1613/conversions/Publisher-logo-thumbnail.jpg\"}',
        1,
        '{\"country\":\"Officiis consectetur\",\"city\":\"Et eveniet omnis ad\",\"state\":\"Nobis et asperiores\",\"zip\":\"72091\",\"street_address\":\"Eum quisquam irure m\"}',
        '{\"notifications\":{\"email\":null},\"contact\":\"5799789787\",\"website\":\"https:\\/\\/www.bawiwomanor.org\",\"socials\":[],\"location\":[]}',
        NULL,
        '2021-12-07 16:47:07',
        '2023-11-22 12:01:11'
    ),
    (
        10,
        1,
        'Drake Cain',
        'quirk-and-charm-boutique',
        'Lorem sapiente accus',
        '{\"thumbnail\":\"https:\\/\\/pickbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/1723\\/conversions\\/Gadget-banner-thumbnail.jpg\",\"original\":\"https:\\/\\/pickbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/1723\\/Gadget-banner.png\",\"id\":1723,\"file_name\":\"Gadget-banner.png\"}',
        '{\"thumbnail\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/343\\/conversions\\/logo5-thumbnail.jpg\",\"original\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/343\\/logo5.png\",\"id\":343,\"file_name\":\"logo5.png\"}',
        1,
        '{\"country\":\"Occaecat ut excepteu\",\"city\":\"Voluptatem amet po\",\"state\":\"Odio aut ea neque re\",\"zip\":\"22395\",\"street_address\":\"Voluptatem deleniti\"}',
        '{\"notifications\":{\"email\":null},\"contact\":\"78298867\",\"website\":\"https:\\/\\/www.puk.biz\",\"socials\":[],\"location\":[]}',
        NULL,
        '2023-10-02 08:38:16',
        '2023-11-23 03:56:51'
    ),
    (
        11,
        1,
        'Marny Rose',
        'cozy-couture-corner',
        'Voluptatem odio qui',
        '{\"thumbnail\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/329\\/conversions\\/shop-banner010-thumbnail.jpg\",\"original\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/329\\/shop-banner010.png\",\"id\":329,\"file_name\":\"shop-banner010.png\"}',
        '{\"thumbnail\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/328\\/conversions\\/logo01-thumbnail.jpg\",\"original\":\"https:\\/\\/chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/328\\/logo01.png\",\"id\":328,\"file_name\":\"logo01.png\"}',
        1,
        '{\"country\":\"Quae qui dolore ea s\",\"city\":\"Laboris voluptatibus\",\"state\":\"Ut rerum necessitati\",\"zip\":\"25196\",\"street_address\":\"Quis eligendi aliqua\"}',
        '{\"notifications\":{\"email\":null},\"contact\":\"53290798686\",\"website\":\"https:\\/\\/www.wajok.mobi\",\"socials\":[],\"location\":[]}',
        NULL,
        '2023-10-02 17:42:55',
        '2023-11-22 11:59:01'
    );