INSERT INTO `terms_and_conditions` (
        `id`,
        `user_id`,
        `shop_id`,
        `title`,
        `slug`,
        `description`,
        `type`,
        `issued_by`,
        `is_approved`,
        `language`,
        `deleted_at`,
        `created_at`,
        `updated_at`
    )
VALUES (
        6,
        6,
        11,
        'Two driven jocks help fax my big quiz.',
        'two-driven-jocks-help-fax-my-big-quiz',
        '<p><span style=\"color: rgb(102, 102, 102);\">Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</span></p>',
        'shop',
        'Marny Rose',
        1,
        'en',
        NULL,
        '2024-01-14 04:20:03',
        '2024-01-14 04:33:42'
    ),
    (
        7,
        6,
        11,
        'The bedding was hardly',
        'the-bedding-was-hardly-able-to-cover',
        '<p><span style=\"color: rgb(102, 102, 102);\">A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.</span></p>',
        'shop',
        'Marny Rose',
        1,
        'en',
        NULL,
        '2024-01-14 04:34:16',
        '2024-01-14 04:34:38'
    ),
    (
        8,
        6,
        11,
        'A small river named Duden',
        'a-small-river-named-duden',
        '<p><span style=\"color: rgb(102, 102, 102);\">When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then</span></p>',
        'shop',
        'Marny Rose',
        1,
        'en',
        NULL,
        '2024-01-14 04:35:11',
        '2024-01-14 04:35:17'
    ),
    (
        9,
        6,
        10,
        'Lorem ipsum dolor sit amet',
        'lorem-ipsum-dolor-sit-amet',
        '<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p><p>Aenean commodo ligula eget dolor. Aenean massa.</p><p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p><p>Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</p><p>Nulla consequat massa quis enim.</p><p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.</p><p>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo.</p><p>Nullam dictum felis eu pede mollis pretium.</p><p>Integer tincidunt. Cras dapibus.</p><p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.</p><p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.</p><p>Aliquam lorem ante, dapibus in, viverra quis, feugiat a,</p>',
        'shop',
        'Drake Cain',
        1,
        'en',
        NULL,
        '2024-01-14 05:37:41',
        '2024-01-14 11:58:32'
    ),
    (
        10,
        6,
        9,
        'Nemo enim ipsam voluptatem quia',
        'nemo-enim-ipsam-voluptatem-quia',
        '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p><p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p><p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p><p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex</p>',
        'shop',
        'Claire Miranda',
        1,
        'en',
        NULL,
        '2024-01-14 05:38:26',
        '2024-01-14 11:58:42'
    ),
    (
        11,
        6,
        2,
        'To take a trivial example',
        'to-take-a-trivial-example',
        '<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.</p><p>No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.</p><p>Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.</p><p>To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it?</p><p>But who has any right to find fault with a man who chooses to enjoy a pleasure</p>',
        'shop',
        'Urban Threads Emporium',
        1,
        'en',
        NULL,
        '2024-01-14 05:39:03',
        '2024-01-14 11:58:53'
    ),
    (
        12,
        6,
        1,
        'Lor separat existentie es un myth.',
        'lor-separat-existentie-es-un-myth',
        '<p>Li Europan lingues es membres del sam familie.</p><p>Lor separat existentie es un myth.</p><p>Por scientie, musica, sport etc, litot Europa usa li sam vocabular.</p><p>Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules.</p><p>Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores.</p><p>At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.</p><p>Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues.</p><p>Li nov lingua franca va esser plu simplic e regulari quam li existent Europan lingues.</p><p>It va esser tam simplic quam Occidental in fact, it va esser Occidental.</p><p>A un Angleso it va semblar un simplificat Angles, quam un skeptic Cambridge amico dit me que Occidental es.</p><p>Li Europan lingues es membres del sam familie.</p><p>Lor separat existentie es un myth.</p><p>Por scientie, musica,</p>',
        'shop',
        'Blythe Knowles',
        1,
        'en',
        NULL,
        '2024-01-14 05:39:34',
        '2024-01-14 12:00:56'
    ),
    (
        13,
        6,
        8,
        'Their separate existence is a myth.',
        'their-separate-existence-is-a-myth',
        '<p>The European languages are members of the same family.</p><p>Their separate existence is a myth.</p><p>For science, music, sport, etc, Europe uses the same vocabulary.</p><p>The languages only differ in their grammar, their pronunciation and their most common words.</p><p>Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators.</p><p>To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words.</p><p>If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.</p><p>The new common language will be more simple and regular than the existing European languages.</p><p>It will be as simple as Occidental; in fact, it will be Occidental.</p><p>To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is.</p><p>The European languages are members of the</p>',
        'shop',
        'Lavinia Burch',
        1,
        'en',
        NULL,
        '2024-01-14 05:41:25',
        '2024-01-14 12:00:26'
    ),
    (
        14,
        6,
        7,
        'It is a paradisematic country',
        'it-is-a-paradisematic-country',
        '<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p><p>Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p><p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p><p>It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p><p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p><p>The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen.</p><p>She packed her seven versalia, put her initial into the belt and made herself</p>',
        'shop',
        'Xena Ochoa',
        1,
        'en',
        NULL,
        '2024-01-14 05:42:00',
        '2024-01-14 12:00:12'
    ),
    (
        15,
        6,
        6,
        'I am alone, and feel the charm',
        'i-am-alone-and-feel-the-charm',
        '<p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.</p><p>I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.</p><p>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents.</p><p>I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now.</p><p>When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a</p>',
        'shop',
        'Ethereal Essence Boutique',
        1,
        'en',
        NULL,
        '2024-01-14 05:42:31',
        '2024-01-14 11:59:59'
    ),
    (
        16,
        6,
        5,
        'The bedding was hardly able',
        'the-bedding-was-hardly-able',
        '<p>One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.</p><p>He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections.</p><p>The bedding was hardly able to cover it and seemed ready to slide off any moment.</p><p>His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked.</p><p>\"What\'s happened to me?</p><p>\" he thought. It wasn\'t a dream.</p><p>His room, a proper human room although a little too small, lay peacefully between its four familiar walls.</p><p>A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed</p>',
        'shop',
        'Sleek Streetwear Co.',
        1,
        'en',
        NULL,
        '2024-01-14 05:42:58',
        '2024-01-14 11:59:48'
    ),
    (
        17,
        6,
        4,
        'The quick, brown fox jumps over a lazy dog.',
        'the-quick-brown-fox-jumps-over-a-lazy-dog',
        '<p>The quick, brown fox jumps over a lazy dog.</p><p>DJs flock by when MTV ax quiz prog.</p><p>Junk MTV quiz graced by fox whelps.</p><p>Bawds jog, flick quartz, vex nymphs.</p><p>Waltz, bad nymph, for quick jigs vex!</p><p>Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox.</p><p>Bright vixens jump; dozy fowl quack.</p><p>Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim.</p><p>Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex.</p><p>Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs!</p><p>\"Now fax quiz Jack! \" my brave ghost pled.</p><p>Five quacking zephyrs jolt my wax bed. Flummoxed by job, kvetching W.</p><p>zaps Iraq. Cozy sphinx waves quart jug of bad milk. A very bad quack might jinx zippy fowls.</p><p>Few quips galvanized the mock jury box. Quick brown dogs jump over the lazy fox. The jay, pig,</p>',
        'shop',
        'Boho Bliss Emporium',
        1,
        'en',
        NULL,
        '2024-01-14 05:43:36',
        '2024-01-14 11:59:35'
    ),
    (
        18,
        1,
        NULL,
        'The Big Oxmox advised her',
        'the-big-oxmox-advised-her',
        'The Website is provided \"as is\" and \"as available\" without any warranties, either expressed or implied. Pickbazar shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from the use or inability to use the Website.',
        'global',
        'Super Admin',
        1,
        'en',
        NULL,
        '2024-01-14 11:52:22',
        NULL
    ),
    (
        23,
        1,
        NULL,
        'Five quacking zephyrs jolt my',
        'five-quacking-zephyrs-jolt-my',
        '<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p><p>Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p><p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p><p>It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p><p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p><p>The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen.</p><p>She packed her seven versalia, put her initial into the belt and made herself</p>',
        'global',
        'Super Admin',
        1,
        'en',
        NULL,
        '2024-01-14 18:04:26',
        '2024-01-14 18:12:29'
    );